local_backend: true
backend:
  name: github
  repo: SirwanAfifi/sirwanafifi.github.io
  # optional, defaults to master
  # branch: main
collections:
  - name: "blogEn" # Used in routes, e.g., /admin/collections/blog
    label: "English Blog" # Used in the UI
    # folder: "blog/en/" # The path to the folder where the documents are stored
    folder: "blog_astro/src/content/blog/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - label: "Date"
        name: "start"
        widget: "datetime"
        default: "2019-01-25"
        # date_format: "DD/MM/YYYY" # e.g. 24.12.2021
        # time_format: "HH:mm" # e.g. 21:07
        format: "MMMM"
        # picker_utc: false
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "post",
        }
      - { label: "Draft", name: "draft", widget: "hidden", default: false }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Category", name: "category", widget: "hidden" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Lang", name: "lang", widget: "hidden", default: "en" }
      - { label: "Image", name: "image", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
media_folder: "img" # Location where files will be stored in the repo
public_folder: "img" # The src attribute for uploaded media
